config/routes.rb
Rails.application.routes.draw do
  
  resources :transactions

  devise_scope :user do
  get "/users/sign_up",  :to => 'pages#home'
  get "/users/password/new",  :to => 'pages#home'
  end

  devise_for :users
  root "pages#home"
  
  resources :stocks

end

app/models/stock.rb
class Stock < ActiveRecord::Base
	attr_accessor :last_trade_price, :ask_real_time, :change_in_percent
	has_many :transactions
	validates :symbol, presence: true
	validates :symbol, uniqueness: true
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	require 'restclient'

	belongs_to :user
	belongs_to :stock
	
	after_save :update_stock_status

	attr_accessor :diff_from_current_price

	monetize :gross_proceeds_cents, :allow_nil => true, with_model_currency: :currency
	monetize :tax_cents, :allow_nil => true, with_model_currency: :currency
	monetize :net_proceeds_cents, :allow_nil => true, with_model_currency: :currency
	monetize :commission_cents, :allow_nil => true, with_model_currency: :currency
	monetize :rate_cents, :allow_nil => true, with_model_currency: :currency

	scope :from_nasdaq, -> { includes(:stock).where(stocks: { exchange:  'Nasdaq'})}
	scope :from_tase, -> { includes(:stock).where(stocks: { exchange:  'TASE'})}
	scope :by_active_stock, -> { order('stocks.active_stock DESC') } 
	scope :most_recent_transaction, -> { order('stocks.symbol','transactions.value_date desc').select('DISTINCT ON(stocks.symbol) *')}

	def update_stock_status
		sale_quantity = Transaction.all.includes(:stock).where(stocks:{symbol: self.stock.symbol}).where(transaction_type: 'Sale').sum(:quantity)
		buy_quantity = Transaction.all.includes(:stock).where(stocks:{symbol: self.stock.symbol}).where(transaction_type: 'Buy').sum(:quantity)
		if sale_quantity == buy_quantity
			self.stock.active_stock = false
		else
			self.stock.active_stock = true
		end
		self.stock.save!
	end

	def self.get_nasdaq_data_from_yahoo(transactions)
  	all_symbols = transactions.map(&:stock).map(&:symbol)
  	data = YahooFinance.quotes(all_symbols, [:symbol,:ask_real_time,:last_trade_price,:change_in_percent], { raw: false })
	  	data.each_with_index do |stock, index|
	  		transactions[index].stock.ask_real_time = stock.ask_real_time
	  		transactions[index].stock.last_trade_price = stock.last_trade_price
	  		transactions[index].stock.change_in_percent = stock.change_in_percent
	  	end
  	transactions
  	end

  	def self.get_tase_data_from_bizportal(transactions)	
  		all_urls = transactions.map(&:stock).map(&:graph_url)
  		all_urls.each_with_index do |url,index|
  			doc = Nokogiri::HTML(RestClient.get(url))
  			data = doc.xpath('//*[@id="container1"]/div[9]/div[2]/div[1]').text.split(/[\r\n]+/)
  			transactions[index].stock.last_trade_price = data[0].gsub(/[^\d\.]/, '').to_f
  			transactions[index].stock.change_in_percent = data[1].gsub(/[^\d\.]/, '').to_f
  		end
  		transactions
  	end

  	def self.get_rate_diff(transactions)
  		transactions.each do |transaction|
  			transaction.diff_from_current_price = transaction.stock.last_trade_price.to_f / transaction.rate.to_f - 1
  		end
	transactions
  	end

  	def self.prepare_nasdaq_online_data(transactions)
  		transactions = get_nasdaq_data_from_yahoo(transactions)
  		transactions = get_rate_diff(transactions)
  	end

  	def self.prepare_tase_online_data(transactions)
  		transactions = get_tase_data_from_bizportal(transactions)
  		transactions = get_rate_diff(transactions)
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 before_action :authenticate_user!

  def home
	@nasdaq_transactions = Transaction.prepare_nasdaq_online_data(Transaction.from_nasdaq.most_recent_transaction)
  	@tase_transactions = Transaction.prepare_tase_online_data(Transaction.from_tase.most_recent_transaction)
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @transactions = Transaction.where(:user_id => current_user, :stock_id => @stock.id).order(value_date: :desc)
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:name, :symbol, :description, :exchange, :graph_url,:num)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @transactions = Transaction.all.where(:user_id => current_user)
    respond_with(@transactions)
  end

  def show
    respond_with(@transaction)
  end

  def new
    @transaction = Transaction.new
    @stocks = Stock.all
    respond_with(@transaction)
  end

  def edit
    @stocks = Stock.all
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.save
    respond_with(@transaction)
  end

  def update
    @transaction.update(transaction_params)
    respond_with(@transaction)
  end

  def destroy
    @transaction.destroy
    respond_with(@transaction)
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:transaction_type, :quantity, :rate, :currency, :gross_proceeds, :tax, :commission, :net_proceeds, :registration_date, :charge_date, :value_date, :user_id,:stock_id).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Mystocks</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li><%= link_to "Dashboard", root_path %></li>
            <li><%= link_to "Transaction", transactions_path %></li>
            <li><%= link_to "Stocks", stocks_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mystocks</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://d33t3vvu2t2yu5.cloudfront.net/tv.js"></script>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<% flash.each do |type,message| %>
	<div class="alert alert-info fade-in">
	<button class="close" data-dismiss="alert">x </button>
	<%= message %>
	</div> 
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/_info.html.haml
%table{:class=>"table table-bordered transaction-info"}
  %thead
    %tr
      %th Symbol
      %th Number
      %th Active
      %th Transaction Type
      %th Transaction Date
      %th Transaction Rate
      %th Current Rate
      %th Rate diff
      %th Change from yesterday
    %tbody
      - transactions.each do |transaction| 
        %tr
          %td{:class=>'col-md-2'}=link_to transaction.stock.symbol, stock_path( Stock.find_by_symbol(transaction.stock.symbol))
          %td=transaction.stock.num
          %td=transaction.stock.active_stock
          %td=transaction.transaction_type
          %td=transaction.value_date
          %td=humanized_money_with_symbol transaction.rate
          %td=transaction.stock.last_trade_price
          %td=number_to_percentage(transaction.diff_from_current_price * 100, precision: 2) unless transaction.diff_from_current_price == nil
          %td=transaction.stock.change_in_percent
          

app/views/pages/home.html.haml
%h1{:class => "text-center" } Dashboard
.row
 .col-md-12
  %h3{:class => "text-left" } Nasdaq stocks
  =render 'info', :transactions => @nasdaq_transactions
  %h3{:class => "text-left" } TASE stocks   
  =render 'info', :transactions => @tase_transactions

  

app/views/stocks/_form.html.haml
= simple_form_for(@stock, html: {class: "form-signin"}) do |f|
  = f.error_notification
  = f.input :name,label: false, placeholder:"Stocks's Name",required: true
  = f.input :symbol,label: false, placeholder:"Symbol",required: true
  = f.input :num,label: false, placeholder:"Number",required: true
  = f.input :description,label: false, placeholder:"Description",required: true, input_html: { rows:5}
  = f.input :exchange,collection: ['Nasdaq','TASE'],label: false,required: true,default: 'Nasdaq'
  = f.input :graph_url,label: false, placeholder:"Graph url"
  = f.button :submit, class: "btn btn-primary btn-block"

app/views/stocks/_transactions.html.haml
%table{:class => "table table-bordered transaction-info" }
  %thead
    %tr
      %th Date
      %th Type
      %th Rate
      %th Quantity
      %th Gross Proceeds
      %th Net Proceeds
      %th Tax
      %th Commission
  %tbody
  -@transactions.each do |transactions|
    %tr
      %td= transactions.value_date
      %td= transactions.transaction_type
      %td= humanized_money_with_symbol transactions.rate
      %td= transactions.quantity
      %td= humanized_money_with_symbol transactions.gross_proceeds
      %td= humanized_money_with_symbol transactions.net_proceeds
      %td= humanized_money_with_symbol transactions.tax
      %td= humanized_money_with_symbol transactions.commission

app/views/stocks/edit.html.haml
%h1 Editing stock
=render 'form'
=link_to 'Show', @stock
|
=link_to 'Back', stocks_path

app/views/stocks/index.html.haml
%h1 Listing stocks
%p{:class =>"text-right"}
  =link_to 'New Stock', new_stock_path,:class => 'btn btn-primary btn-lg'
%table{:class=>"table table-striped"}
  %thead
    %tr
      %th Name
      %th Symbol
      %th Number
      %th Description
      %th Exchange
      %th Graph url
      %th{:colspan=>"3"}
  %tbody
    -@stocks.each do |stock|
      %tr
        %td= stock.name
        %td= stock.symbol
        %td= stock.num
        %td= stock.description
        %td= stock.exchange
        %td= stock.graph_url
        %td= link_to 'Show', stock,:class => 'btn btn-mini'
        %td= link_to 'Edit', edit_stock_path(stock), :class => 'btn btn-mini'
        %td= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn danger'
%br

app/views/stocks/new.html.haml
%h1 New stock
=render 'form'
=link_to 'Back', stocks_path

app/views/stocks/show.html.haml
.row
  .col-lg-6
    %h3{:class => "text-left"} Stock Info
    %p
      %strong Name: 
      =@stock.name
    %p
      %strong Symbol: 
      =@stock.symbol
    %p
      %strong Number: 
      =@stock.num
    %p
      %strong Description: 
      =@stock.description
    %p
      %strong Exchange: 
      =@stock.exchange
    %h3{:class=>'text-left'} Transactions
    =render "transactions"
  .col-lg-6.stock-right-side
    -if @stock.exchange == "Nasdaq"
      :javascript 
        $(window).load(loadTradingView('#{@stock.symbol}'));
    -else
      %p= link_to "Graph",@stock.graph_url,:target => "_blank"

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>
    <%= f.input :transaction_type,collection:['Sale','Buy','Dividend'],label:false,required: true,default:'Sale' %>
    <%= f.input :stock_id,collection:@stocks,:label_method => :symbol,:value_method => :id,label:false,required: true %>
    <%= f.input :quantity,label: false, placeholder:"Quantity",required: true %>
    <%= f.input :rate,label: false, placeholder:"Rate",required: true %>
    <%= f.input :currency,collection: ['USD','ILS'],label: false,required: true,default:'USD' %>
    <%= f.input :gross_proceeds,label: false, placeholder:"Gross Proceeds" %>
    <%= f.input :tax,label: false, placeholder:"Tax",required: true %>
    <%= f.input :commission,label: false, placeholder:"Commission"%>
    <%= f.input :net_proceeds,label: false, placeholder:"Net Proceeds" %>
    <%= f.input :registration_date,label: false, placeholder:"Registration Date", :as => :date_picker %>
    <%= f.input :charge_date,label: false, placeholder:"Charge Date",:as => :date_picker %>
    <%= f.input :value_date,label: false, placeholder:"Value Date",:as => :date_picker %>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>All transactions</h1>
<p class="text-right" > <%= link_to 'New Transaction', new_transaction_path,:class => 'btn btn-primary btn-lg' %> </p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th>Stock</th>
      <th>Quantity</th>
      <th>Rate</th>
      <th>Currency</th>
      <th>Gross proceeds</th>
      <th>Tax</th>
      <th>Commission</th>
      <th>Net proceeds</th>
      <th>Registration date</th>
      <th>Charge date</th>
      <th>Value date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.transaction_type %></td>
        <td><%= transaction.stock.symbol %></td>
        <td><%= transaction.quantity %></td>
        <td><%= transaction.rate %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.gross_proceeds %></td>
        <td><%= transaction.tax %></td>
        <td><%= transaction.commission %></td>
        <td><%= transaction.net_proceeds %></td>
        <td><%= transaction.registration_date %></td>
        <td><%= transaction.charge_date %></td>
        <td><%= transaction.value_date %></td>
        <td><%= link_to 'Show', transaction,:class => 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction),:class => 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/new.html.erb
<h1 class="text-center">New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @transaction.transaction_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction.stock.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @transaction.rate %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @transaction.currency %>
</p>

<p>
  <strong>Gross proceeds:</strong>
  <%= @transaction.gross_proceeds %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @transaction.tax %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @transaction.commission %>
</p>

<p>
  <strong>Net proceeds:</strong>
  <%= @transaction.net_proceeds %>
</p>

<p>
  <strong>Registration date:</strong>
  <%= @transaction.registration_date %>
</p>

<p>
  <strong>Charge date:</strong>
  <%= @transaction.charge_date %>
</p>

<p>
  <strong>Value date:</strong>
  <%= @transaction.value_date %>
</p>

<p class="text-left" > <%= link_to 'Edit Transaction', edit_transaction_path(@transaction),:class => 'btn btn-primary' %> <%= link_to 'New Transaction', new_transaction_path,:class => 'btn btn-primary' %> </p>